version: "3.9"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  server:
    image: my_server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - .:/olx
    ports:
     - 8000:8000
    environment:
      - REDIS_HOST=redis_server
      - REDIS_PORT=6379
      - REDIS_DB=1
    depends_on:
      - redis
      - migration
  migration:
    image: migration
    build:
      context: .
      dockerfile: Dockerfile.migrations
    volumes:
    - .:/olx

